//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.12.18 at 11:28:54 AM CET 
//


package org.apache.pluto.descriptors.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import org.apache.pluto.descriptors.common.InitParamDD;
import org.apache.pluto.descriptors.common.SecurityRoleRefDD;
import org.apache.pluto.descriptors.portlet.PortletDD;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sun.java.xml.ns.portlet.portlet_app_2_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * DD definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PortletDDSecurityRoleRef_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "security-role-ref");
    private final static QName _PortletDDInitParam_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "init-param");
    
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.java.xml.ns.portlet.portlet_app_2_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InitParamDD }
     * 
     */
    public InitParamDD createInitParamDD() {
        return new InitParamDD();
    }

    /**
     * Create an instance of {@link SecurityRoleRefDD }
     * 
     */
    public SecurityRoleRefDD createSecurityRoleRefDD() {
        return new SecurityRoleRefDD();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InitParamDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "init-param", scope = PortletDD.class)
    public JAXBElement<InitParamDD> createPortletDDInitParam(InitParamDD value) {
        return new JAXBElement<InitParamDD>(_PortletDDInitParam_QNAME, InitParamDD.class, PortletDD.class, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityRoleRefDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "security-role-ref", scope = PortletDD.class)
    public JAXBElement<SecurityRoleRefDD> createPortletDDSecurityRoleRef(SecurityRoleRefDD value) {
        return new JAXBElement<SecurityRoleRefDD>(_PortletDDSecurityRoleRef_QNAME, SecurityRoleRefDD.class, PortletDD.class, value);
    }
}
