//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.12.18 at 11:28:54 AM CET 
//


package org.apache.pluto.descriptors.portlet;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sun.java.xml.ns.portlet.portlet_app_2_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * DD definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PortletDDPortletPreferences_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "portlet-preferences");
    private final static QName _PortletDDSupportedPublishingEvent_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "supported-publishing-event");
    private final static QName _PortletDDExpirationCache_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "expiration-cache");
    private final static QName _PortletDDSupportedProcessingEvent_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "supported-processing-event");
    private final static QName _PortletDDDescription_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "description");
    private final static QName _PortletDDResourceBundle_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "resource-bundle");
    private final static QName _PortletDDDisplayName_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "display-name");
    private final static QName _PortletDDPortletClass_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "portlet-class");
    private final static QName _PortletDDSupportedSharedRenderParameter_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "supported-shared-render-parameter");
    private final static QName _PortletDDPortletInfo_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "portlet-info");
    private final static QName _PortletDDPortletName_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "portlet-name");
    private final static QName _PortletDDSupports_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "supports");
    private final static QName _PortletDDSupportedLocale_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "supported-locale");
    private final static QName _PortletApp_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "portlet-app");
    private final static QName _PortletApp1_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd", "portlet-app");
    private final static QName _Portlet1DD_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd", "portlet");
    private final static QName _PortletDD_QNAME = new QName("http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", "portlet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sun.java.xml.ns.portlet.portlet_app_2_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PortletDD }
     * 
     */
    public PortletDD createPortletDD() {
        return new PortletDD();
    }

//    /**
//     * Create an instance of {@link PortletCollectionDD }
//     * 
//     */
//    public PortletCollectionDD createPortletCollectionDD() {
//        return new PortletCollectionDD();
//    }
//
//    /**
//     * Create an instance of {@link PreferenceDD }
//     * 
//     */
//    public PreferenceDD createPreferenceDD() {
//        return new PreferenceDD();
//    }

    /**
     * Create an instance of {@link PortletInfoDD }
     * 
     */
    public PortletInfoDD createPortletInfoDD() {
        return new PortletInfoDD();
    }

    /**
     * Create an instance of {@link EventDefinitionDD }
     * 
     */
    public EventDefinitionDD createEventDefinitionDD() {
        return new EventDefinitionDD();
    }

//    /**
//     * Create an instance of {@link SecurityConstraintDD }
//     * 
//     */
//    public SecurityConstraintDD createSecurityConstraintDD() {
//        return new SecurityConstraintDD();
//    }
//
//    /**
//     * Create an instance of {@link ShortTitleDD }
//     * 
//     */
//    public ShortTitleDD createShortTitleDD() {
//        return new ShortTitleDD();
//    }

//    /**
//     * Create an instance of {@link DescriptionDD }
//     * 
//     */
//    public DescriptionDD createDescriptionDD() {
//        return new DescriptionDD();
//    }

    /**
     * Create an instance of {@link ExpirationCacheDD }
     * 
     */
    public ExpirationCacheDD createExpirationCacheDD() {
        return new ExpirationCacheDD();
    }
//
//    /**
//     * Create an instance of {@link DisplayNameDD }
//     * 
//     */
//    public DisplayNameDD createDisplayNameDD() {
//        return new DisplayNameDD();
//    }

//    /**
//     * Create an instance of {@link SupportedLocaleDD }
//     * 
//     */
//    public SupportedLocaleDD createSupportedLocaleDD() {
//        return new SupportedLocaleDD();
//    }
//
//    /**
//     * Create an instance of {@link UserDataConstraintDD }
//     * 
//     */
//    public UserDataConstraintDD createUserDataConstraintDD() {
//        return new UserDataConstraintDD();
//    }
//
//    /**
//     * Create an instance of {@link TitleDD }
//     * 
//     */
//    public TitleDD createTitleDD() {
//        return new TitleDD();
//    }
//
//    /**
//     * Create an instance of {@link KeywordsDD }
//     * 
//     */
//    public KeywordsDD createKeywordsDD() {
//        return new KeywordsDD();
//    }
//
//    /**
//     * Create an instance of {@link FilterDD }
//     * 
//     */
//    public FilterDD createFilterDD() {
//        return new FilterDD();
//    }

    /**
     * Create an instance of {@link PortletAppDD }
     * 
     */
    public PortletAppDD createPortletAppDD() {
        return new PortletAppDD();
    }

//    /**
//     * Create an instance of {@link RoleLinkDD }
//     * 
//     */
//    public RoleLinkDD createRoleLinkDD() {
//        return new RoleLinkDD();
//    }

    /**
     * Create an instance of {@link SupportsDD }
     * 
     */
    public SupportsDD createSupportsDD() {
        return new SupportsDD();
    }

    /**
     * Create an instance of {@link PortletPreferencesDD }
     * 
     */
    public PortletPreferencesDD createPortletPreferencesDD() {
        return new PortletPreferencesDD();
    }

//    /**
//     * Create an instance of {@link CacheScopeDD }
//     * 
//     */
//    public CacheScopeDD createCacheScopeDD() {
//        return new CacheScopeDD();
//    }
//
//    /**
//     * Create an instance of {@link PortletModeDD }
//     * 
//     */
//    public PortletModeDD createPortletModeDD() {
//        return new PortletModeDD();
//    }
//
//    /**
//     * Create an instance of {@link CustomWindowStateDD }
//     * 
//     */
//    public CustomWindowStateDD createCustomWindowStateDD() {
//        return new CustomWindowStateDD();
//    }
//
//    /**
//     * Create an instance of {@link PortletNameDD }
//     * 
//     */
//    public PortletNameDD createPortletNameDD() {
//        return new PortletNameDD();
//    }

//    /**
//     * Create an instance of {@link WindowStateDD }
//     * 
//     */
//    public WindowStateDD createWindowStateDD() {
//        return new WindowStateDD();
//    }
//
//    /**
//     * Create an instance of {@link ExpirationTimeDD }
//     * 
//     */
//    public ExpirationTimeDD createExpirationTimeDD() {
//        return new ExpirationTimeDD();
//    }
//
//    /**
//     * Create an instance of {@link ValueDD }
//     * 
//     */
//    public ValueDD createValueDD() {
//        return new ValueDD();
//    }
//
//    /**
//     * Create an instance of {@link CustomPortletModeDD }
//     * 
//     */
//    public CustomPortletModeDD createCustomPortletModeDD() {
//        return new CustomPortletModeDD();
//    }
//
//    /**
//     * Create an instance of {@link ResourceBundleDD }
//     * 
//     */
//    public ResourceBundleDD createResourceBundleDD() {
//        return new ResourceBundleDD();
//    }
//
//    /**
//     * Create an instance of {@link UserAttributeDD }
//     * 
//     */
//    public UserAttributeDD createUserAttributeDD() {
//        return new UserAttributeDD();
//    }
//
//    /**
//     * Create an instance of {@link MimeDDDD }
//     * 
//     */
//    public MimeDDDD createMimeDDDD() {
//        return new MimeDDDD();
//    }
//
//    /**
//     * Create an instance of {@link SharedRenderParameterDD }
//     * 
//     */
//    public SharedRenderParameterDD createSharedRenderParameterDD() {
//        return new SharedRenderParameterDD();
//    }
//
//    /**
//     * Create an instance of {@link FilterMappingDD }
//     * 
//     */
//    public FilterMappingDD createFilterMappingDD() {
//        return new FilterMappingDD();
//    }
//
//    /**
//     * Create an instance of {@link NameDD }
//     * 
//     */
//    public NameDD createNameDD() {
//        return new NameDD();
//    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortletDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd", name = "portlet", scope = PortletAppDD.class)
    public JAXBElement<PortletDD> createPortlet1DD(PortletDD value) {
        return new JAXBElement<PortletDD>(_Portlet1DD_QNAME, PortletDD.class, PortletAppDD.class, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortletDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "portlet", scope = PortletAppDD.class)
    public JAXBElement<PortletDD> createPortletDD(PortletDD value) {
        return new JAXBElement<PortletDD>(_PortletDD_QNAME, PortletDD.class, PortletAppDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortletPreferencesDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "portlet-preferences", scope = PortletDD.class)
    public JAXBElement<PortletPreferencesDD> createPortletDDPortletPreferences(PortletPreferencesDD value) {
        return new JAXBElement<PortletPreferencesDD>(_PortletDDPortletPreferences_QNAME, PortletPreferencesDD.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "supported-publishing-event", scope = PortletDD.class)
    public JAXBElement<QName> createPortletDDSupportedPublishingEvent(QName value) {
        return new JAXBElement<QName>(_PortletDDSupportedPublishingEvent_QNAME, QName.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpirationCacheDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "expiration-cache", scope = PortletDD.class)
    public JAXBElement<ExpirationCacheDD> createPortletDDExpirationCache(ExpirationCacheDD value) {
        return new JAXBElement<ExpirationCacheDD>(_PortletDDExpirationCache_QNAME, ExpirationCacheDD.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "supported-processing-event", scope = PortletDD.class)
    public JAXBElement<QName> createPortletDDSupportedProcessingEvent(QName value) {
        return new JAXBElement<QName>(_PortletDDSupportedProcessingEvent_QNAME, QName.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptionDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "description", scope = PortletDD.class)
    public JAXBElement<String> createPortletDDDescription(String value) {
        return new JAXBElement<String>(_PortletDDDescription_QNAME, String.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceBundleDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "resource-bundle", scope = PortletDD.class)
    public JAXBElement<String> createPortletDDResourceBundle(String value) {
        return new JAXBElement<String>(_PortletDDResourceBundle_QNAME, String.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DisplayNameDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "display-name", scope = PortletDD.class)
    public JAXBElement<String> createPortletDDDisplayName(String value) {
        return new JAXBElement<String>(_PortletDDDisplayName_QNAME, String.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "portlet-class", scope = PortletDD.class)
    public JAXBElement<String> createPortletDDPortletClass(String value) {
        return new JAXBElement<String>(_PortletDDPortletClass_QNAME, String.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "supported-shared-render-parameter", scope = PortletDD.class)
    public JAXBElement<String> createPortletDDSupportedSharedRenderParameter(String value) {
        return new JAXBElement<String>(_PortletDDSupportedSharedRenderParameter_QNAME, String.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortletInfoDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "portlet-info", scope = PortletDD.class)
    public JAXBElement<PortletInfoDD> createPortletDDPortletInfo(PortletInfoDD value) {
        return new JAXBElement<PortletInfoDD>(_PortletDDPortletInfo_QNAME, PortletInfoDD.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortletNameDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "portlet-name", scope = PortletDD.class)
    public JAXBElement<String> createPortletDDPortletName(String value) {
        return new JAXBElement<String>(_PortletDDPortletName_QNAME, String.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SupportsDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "supports", scope = PortletDD.class)
    public JAXBElement<SupportsDD> createPortletDDSupports(SupportsDD value) {
        return new JAXBElement<SupportsDD>(_PortletDDSupports_QNAME, SupportsDD.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SupportedLocaleDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "supported-locale", scope = PortletDD.class)
    public JAXBElement<String> createPortletDDSupportedLocale(String value) {
        return new JAXBElement<String>(_PortletDDSupportedLocale_QNAME, String.class, PortletDD.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortletAppDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd", name = "portlet-app")
    public JAXBElement<PortletAppDD> createPortletApp(PortletAppDD value) {
        return new JAXBElement<PortletAppDD>(_PortletApp_QNAME, PortletAppDD.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortletAppDD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd", name = "portlet-app")
    public JAXBElement<PortletAppDD> createPortletApp1(PortletAppDD value) {
        return new JAXBElement<PortletAppDD>(_PortletApp1_QNAME, PortletAppDD.class, null, value);
    }

}
